### ISSUE TITLE
C-m doesn't work

### ISSUE THREAD

**Issue by mrkkrp** [stephendavidmarsh/control-mode#5]
When the mode is enabled <kbd>C-m</kbd> doesn't work (it should insert new lines or do whatever <kbd>RET</kbd> is bound to).

**Comment by mrkkrp** [comment]
Oh, sorry, I see it's intentional, although I prefer <kbd>m</kbd> to work as <kbd>Cm</kbd>, but I'm sure I can fix it. Why do these exceptions for <kbd>M-m</kbd> and <kbd>M-i</kbd> exist?

**Comment by mrkkrp** [comment]
Is there easy way to make <kbd>m</kbd> work as <kbd>C-m</kbd> and <kbd>i</kbd> as <kbd>C-i</kbd>?

**Comment by stephendavidmarsh** [comment]
It's been a while, but I believe bindings on Ctrl-m and Ctrl-i are ignored to prevent ambiguity. I think you can either make keybindings on Ctrl-TAB and Ctrl-RET, which will then be bound to TAB and RET in control mode, or create bindings in control-mode-keymap (see last paragraph of README.md).

**Comment by mrkkrp** [comment]
I see, I don't usually use <kbd>↵ Enter</kbd> key or <kbd>↹ Tab</kbd> key (the first is useless since we have <kbd>C-m</kbd> and <kbd>C-j</kbd> and the second is swapped with backspace and I use <kbd>C-i</kbd> instead). I'll try to adopt this package into my ergonomic model. It certainly deserves key binding with single key-pressing, like <kbd>↵ Enter</kbd> to activate it. I'm currently experimenting trying understand how I can use it efficiently. Thanks for the package. I'm closing this for now.

**Comment by mrkkrp** [comment]
For future readers, the proper solution is:

```emacs-lisp
(setq control-mode-ignore-events nil)
```
